[package]
name = "parsin"
authors = ["Gabriel Mendieta Hernandez <gmendieta4109@gmail.com>"]
version = "0.1.0"
edition = "2021"
description = "A simple, minimalistic CLI (Command-Line Interface) parser for Rust."
documentation = "https://docs.rs/parsin"

[dependencies]
